# Generated by Django 5.1.7 on 2025-09-13 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='company_avatars/')),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('tech_stack', models.JSONField(default=list)),
                ('focus_areas', models.JSONField(default=list)),
                ('incident_frequency', models.FloatField(default=0.1)),
                ('severity_distribution', models.JSONField(default=dict)),
                ('work_hours_start', models.TimeField(default='09:00')),
                ('work_hours_end', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='completedsimulation',
            name='time_spent',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='company_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='company_avatars/'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('P0', 'Critical - Service Down'), ('P1', 'High - Major Impact'), ('P2', 'Medium - Minor Impact'), ('P3', 'Low - Cosmetic Issue')], max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('affected_services', models.JSONField(default=list)),
                ('error_logs', models.TextField(blank=True)),
                ('monitoring_dashboard_url', models.URLField(blank=True)),
                ('codebase_context', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('solution_type', models.CharField(blank=True, max_length=50)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.company')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_duration_hours', models.PositiveIntegerField(default=8)),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('incidents_resolved', models.PositiveIntegerField(default=0)),
                ('incidents_escalated', models.PositiveIntegerField(default=0)),
                ('incidents_abandoned', models.PositiveIntegerField(default=0)),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('average_resolution_time', models.FloatField(default=0.0)),
                ('rating_change', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('resolution_approach', models.TextField(blank=True)),
                ('code_changes', models.TextField(blank=True)),
                ('commands_executed', models.JSONField(default=list)),
                ('resources_accessed', models.JSONField(default=list)),
                ('was_successful', models.BooleanField(default=False)),
                ('was_root_cause_fix', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.simulationsession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(default=800)),
                ('debugging_skill', models.PositiveIntegerField(default=800)),
                ('system_design', models.PositiveIntegerField(default=800)),
                ('incident_response', models.PositiveIntegerField(default=800)),
                ('communication', models.PositiveIntegerField(default=800)),
                ('total_incidents_resolved', models.PositiveIntegerField(default=0)),
                ('average_resolution_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('company_ratings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
            },
        ),
    ]
