# Generated by Django 5.2.6 on 2025-09-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_company_completedsimulation_time_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_best_practices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_communication',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_correctness_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_feedback',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_grading_method',
            field=models.CharField(default='llm', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_improvement_areas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_problem_solving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentattempt',
            name='llm_technical_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.simulationsession'),
        ),
    ]
